[shortDomain]
    dsn = "root:zm2018@tcp(dev.hn-zm.com:3306)/shortDomain?timeout=1s&readTimeout=1s&writeTimeout=1s&parseTime=true&loc=Local&charset=utf8mb4,utf8"
	# 最大连接数
	active = 20
	# 连接池的闲置连接数
	idle = 10
	idleTimeout ="4h"