
redisExpire = "24h"

[shortDomain]
    name = "shortDomain"
    proto = "tcp"
    addr = "dev.hn-zm.com:6379"
    auth = "zm2018"
    idle = 10
    db = 1
    active = 10
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "10s"
